//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acceso
    {
        public int idAcceso { get; set; }
        public int idUsuario { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public int idLocalidad { get; set; }
    
        public virtual Localidade Localidade { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
