//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagene
    {
        public int idImagen { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoImagen { get; set; }
        public string URL { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual TiposImagen TiposImagen { get; set; }
    }
}
