//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoDonArEntities : DbContext
    {
        public ProyectoDonArEntities()
            : base("name=ProyectoDonArEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acceso> Accesos { get; set; }
        public virtual DbSet<Administradore> Administradores { get; set; }
        public virtual DbSet<Donacione> Donaciones { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Imagene> Imagenes { get; set; }
        public virtual DbSet<Localidade> Localidades { get; set; }
        public virtual DbSet<Organizacione> Organizaciones { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Proyecto> Proyectos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TiposImagen> TiposImagens { get; set; }
        public virtual DbSet<TiposProyecto> TiposProyectos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Texto> Textos { get; set; }
        public virtual DbSet<TiposTexto> TiposTextoes { get; set; }
    }
}
