//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Donaciones = new HashSet<Donacione>();
            this.Imagenes = new HashSet<Imagene>();
            this.Textos = new HashSet<Texto>();
        }
    
        public int idProyecto { get; set; }
        public int idOrganizacion { get; set; }
        public int idEstado { get; set; }
        public int idAdministrador { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<double> MontoDeseado { get; set; }
        public Nullable<double> MontoActual { get; set; }
        public Nullable<int> idTipoProyecto { get; set; }
    
        public virtual Administradore Administradore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacione> Donaciones { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagene> Imagenes { get; set; }
        public virtual Organizacione Organizacione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Texto> Textos { get; set; }
        public virtual TiposProyecto TiposProyecto { get; set; }
    }
}
