//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Texto
    {
        public int idTexto { get; set; }
        public int idProyecto { get; set; }
        public int idTipoTexto { get; set; }
        public string Texto1 { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual TiposTexto TiposTexto { get; set; }
    }
}
