//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Accesos = new HashSet<Acceso>();
            this.Donaciones = new HashSet<Donacione>();
        }
    
        public int idUsuario { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Usuario1 { get; set; }
        public byte[] Contraseña { get; set; }
        public string eMail { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string IdNet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acceso> Accesos { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacione> Donaciones { get; set; }
        public virtual Localidade Localidade { get; set; }
    }
}
